### PR TITLE
Fixed bug in authorization code that prevents any request from going through

### PR DESCRIPTION
**Pull request by ntziolis**
`pass` is available on auth instead of on user

### CODE REVIEW

**Comment by maxnowack** [comment]
I have no idea how I could miss that. Thank you!

**Comment by maxnowack** [comment]
Published with `v1.1.6`

**Comment by ntziolis** [comment]
No worries, any interest in expanding the billwerk lib by including typed webhook handling and responses? I could drop some models in and we could take it from there

**Comment by maxnowack** [comment]
sure! feel free to create a pull request 😊

**Pull request merged**
